# Generated by Django 5.2.4 on 2025-07-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='contributor',
            field=models.ManyToManyField(blank=True, to='core.agent', verbose_name='Contributor'),
        ),
    ]
