# Generated by Django 5.2.4 on 2025-07-19 17:39

import django.core.validators
import markdownfield.models
import partial_date.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_media_contributor"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="review",
            field=markdownfield.models.MarkdownField(blank=True, verbose_name="Review"),
        ),
        migrations.AddField(
            model_name="media",
            name="review_date",
            field=partial_date.fields.PartialDateField(blank=True, null=True, verbose_name="Review date"),
        ),
        migrations.AddField(
            model_name="media",
            name="score",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Detested"),
                    (2, "Hated"),
                    (3, "Disliked"),
                    (4, "Not appreciated"),
                    (5, "Moderately appreciated"),
                    (6, "Appreciated"),
                    (7, "Enjoyed"),
                    (8, "Really enjoyed"),
                    (9, "Loved"),
                    (10, "Adored"),
                ],
                null=True,
                verbose_name="Review score",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("IN_PROGRESS", "In progress"),
                    ("COMPLETED", "Completed"),
                    ("PAUSED", "Paused"),
                    ("DNF", "Did not finish"),
                ],
                default="PLANNED",
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="pub_year",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-4000, "Year must be between -4000 and 2200."),
                    django.core.validators.MaxValueValidator(2200, "Year must be between -4000 and 2200."),
                ],
                verbose_name="Release year",
            ),
        ),
    ]
