# Generated by Django 5.2.4 on 2025-07-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_media_review_media_review_date_media_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='contributor',
        ),
        migrations.AddField(
            model_name='media',
            name='contributors',
            field=models.ManyToManyField(blank=True, to='core.agent', verbose_name='Contributor(s)'),
        ),
    ]
