# Generated by Django 6.0 on 2025-12-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_media_contributor_media_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='media',
            name='score',
            field=models.IntegerField(blank=True, choices=[(1, '1⭐ - Detested'), (2, '2⭐ - Hated'), (3, '3⭐ - Disliked'), (4, '4⭐ - Not appreciated'), (5, '5⭐ - Moderately appreciated'), (6, '6⭐ - Appreciated'), (7, '7⭐ - Enjoyed'), (8, '8⭐ - Really enjoyed'), (9, '9⭐ - Loved'), (10, '10⭐ - Adored')], null=True, verbose_name='Review score'),
        ),
    ]
