# Generated by Django 5.2.4 on 2025-07-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_media_contributor_media_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='media', to='core.agent', verbose_name='Contributor(s)'),
        ),
    ]
