# Generated by Django 6.0 on 2025-12-29 09:06

import markdownfield.models
from django.db import migrations


def populate_review_rendered(apps, _schema_editor):
    """
    Generate HTML for existing reviews.

    This function renders markdown to HTML for all Media objects
    that have a review but no rendered HTML yet.
    """
    Media = apps.get_model("core", "Media")

    # Get all media with non-empty reviews
    medias = Media.objects.filter(review__isnull=False).exclude(review="")

    # Save each one to trigger markdown rendering
    for media in medias:
        media.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_media_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="review_rendered",
            field=markdownfield.models.RenderedMarkdownField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="media",
            name="review",
            field=markdownfield.models.MarkdownField(
                blank=True, rendered_field="review_rendered", verbose_name="Review"
            ),
        ),
        migrations.RunPython(populate_review_rendered, migrations.RunPython.noop),
    ]
