# Generated by Django 6.0.1 on 2026-01-10 10:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def populate_updated_at(apps, _schema_editor):
    """Copy created_at to updated_at for all existing Media and Agent records."""
    Media = apps.get_model("core", "Media")
    Agent = apps.get_model("core", "Agent")

    Media.objects.all().update(updated_at=models.F("created_at"))
    Agent.objects.all().update(updated_at=models.F("created_at"))


def reverse_populate_updated_at(_apps, _schema_editor):
    """Reverse migration: do nothing (we can't restore the original updated_at)."""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_media_external_uri_alter_media_review_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Add updated_at fields with default=now (not auto_now yet)
        migrations.AddField(
            model_name="agent",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="media",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        # Step 2: Populate updated_at from created_at for existing records
        migrations.RunPython(
            code=populate_updated_at,
            reverse_code=reverse_populate_updated_at,
        ),
        # Step 3: Change to auto_now=True
        migrations.AlterField(
            model_name="agent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        # Step 4: Create SavedView model
        migrations.CreateModel(
            name="SavedView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filter_types", models.JSONField(blank=True, default=list)),
                ("filter_statuses", models.JSONField(blank=True, default=list)),
                ("filter_scores", models.JSONField(blank=True, default=list)),
                ("filter_contributor_id", models.IntegerField(blank=True, null=True)),
                ("filter_review_from", models.CharField(blank=True, default="", max_length=20)),
                ("filter_review_to", models.CharField(blank=True, default="", max_length=20)),
                ("filter_has_review", models.CharField(blank=True, default="", max_length=10)),
                ("filter_has_cover", models.CharField(blank=True, default="", max_length=10)),
                ("sort", models.CharField(default="-review_date", max_length=50)),
                ("view_mode", models.CharField(default="grid", max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved view",
                "verbose_name_plural": "Saved views",
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
