# Generated by Django 6.0.1 on 2026-01-17 14:16

import django.utils.timezone
from django.db import migrations, models
from django.db.models import Count


def clean_agent_names_forward(apps, schema_editor):
    """
    Clean Agent.name values before adding max_length=100 and unique constraint.

    This function:
    1. Truncates names longer than 100 characters
    2. Resolves duplicate names by appending a counter suffix (_1, _2, etc.)

    For duplicates, the Agent with the lowest ID keeps the original name,
    and subsequent duplicates get renamed with a suffix.
    """
    Agent = apps.get_model("core", "Agent")
    db_alias = schema_editor.connection.alias
    max_length = 100

    # Step 1: Truncate names longer than max_length
    for agent in Agent.objects.using(db_alias).all():
        if len(agent.name) > max_length:
            agent.name = agent.name[:max_length]
            agent.save(update_fields=["name"])

    # Step 2: Find and resolve duplicate names (including those created by truncation)
    duplicate_names = list(
        Agent.objects.using(db_alias)
        .values("name")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
        .values_list("name", flat=True)
    )

    for name in duplicate_names:
        # Get all agents with this name, ordered by ID (oldest first)
        agents = list(Agent.objects.using(db_alias).filter(name=name).order_by("id"))

        if len(agents) <= 1:
            continue

        # The first agent (lowest ID) keeps the original name
        # Subsequent agents get renamed with a suffix
        for idx, agent in enumerate(agents[1:], start=1):
            # Generate a unique name with suffix
            suffix = f"_{idx}"
            # Ensure the new name fits within max_length
            base_name = name[: max_length - len(suffix)]
            new_name = f"{base_name}{suffix}"

            # Handle edge case: if new_name already exists, increment counter
            counter = idx
            while Agent.objects.using(db_alias).filter(name=new_name).exists():
                counter += 1
                suffix = f"_{counter}"
                base_name = name[: max_length - len(suffix)]
                new_name = f"{base_name}{suffix}"

            agent.name = new_name
            agent.save(update_fields=["name"])


def reverse_noop(_apps, _schema_editor):
    """
    Reverse operation is a no-op.

    We cannot restore deleted duplicates or their original relations.
    """


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_agent_updated_at_media_updated_at_savedview"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AlterModelOptions(
            name="agent",
            options={"verbose_name": "Agent", "verbose_name_plural": "Agents"},
        ),
        migrations.RunPython(
            clean_agent_names_forward,
            reverse_code=reverse_noop,
        ),
        migrations.AlterField(
            model_name="agent",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="media",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="media", to="core.tag", verbose_name="Tags"),
        ),
    ]
