# Generated by Django 6.1.1 on 2026-09-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_tag_alter_agent_options_alter_agent_name_media_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedview",
            name="filter_tag_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
