# Generated by Django 6.1.1 on 2026-09-24 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_savedview_filter_tag_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedview",
            name="view_mode",
        ),
    ]
