# Generated by Django 6.1.1 on 2026-09-25 15:42

from django.db import migrations, models
from django.db.models import Q

from core.models import dominant_color


def populate_cover_color(apps, _schema_editor):
    """Pick the colour of the existing covers."""
    Media = apps.get_model("core", "Media")
    for media in Media.objects.exclude(Q(cover__isnull=True) | Q(cover="")):
        media.cover_color = dominant_color(media.cover)
        media.cover.close()
        media.save(update_fields=["cover_color"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_remove_savedview_view_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="cover_color",
            field=models.CharField(blank=True, default="", editable=False, max_length=7),
        ),
        migrations.RunPython(populate_cover_color, migrations.RunPython.noop),
    ]
