# Generated by Django 6.1.1 on 2026-09-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_compress_covers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("BOOK", "Book"),
                    ("GAME", "Video game"),
                    ("MUSIC", "Music"),
                    ("COMIC", "Comic"),
                    ("FILM", "Film"),
                    ("TV", "TV series"),
                    ("PERF", "Show/performance"),
                    ("BROADCAST", "Broadcast"),
                ],
                verbose_name="Media type",
            ),
        ),
    ]
