# Generated by Django 6.1.1 on 2026-10-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_media_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedview",
            name="search",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
