# Generated by Django 6.1.1 on 2026-10-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_savedview_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedview",
            name="filter_release_from",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="savedview",
            name="filter_release_to",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
