# Generated by Django 2.2.13 on 2020-08-29 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='object id')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='rating')),
                ('review', djrichtextfield.models.RichTextField(blank=True, null=True, verbose_name='review')),
                ('date_started', models.DateField(blank=True, null=True, verbose_name='started')),
                ('date_finished', models.DateField(blank=True, null=True, verbose_name='finished')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
