# Generated by Django 2.2.13 on 2020-08-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20200830_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='finished_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Done'), (1, 'Abandoned'), (2, 'Finished')], null=True, verbose_name='finished status'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Detested'), (2, 'Hated'), (3, "Didn't like"), (4, "Didn't really like"), (5, 'Moderately enjoyed'), (6, 'Enjoyed'), (7, 'Liked'), (8, 'Liked a lot'), (9, 'Loved'), (10, 'Adored')], null=True, verbose_name='rating'),
        ),
    ]
